### ISSUE TITLE
cdk deploy QAChatDeployStack fail, 2 validation errors detected

### ISSUE THREAD

**Issue by taylord0ng** [aws-samples/private-llm-qa-bot#125]
According this https://catalog.us-east-1.prod.workshops.aws/workshops/158a2497-7cbe-4ba4-8bee-2307cb01c08a/en-US/2-prepration, when run cdk deploy, 2 validation errors detected
```
11:49:52 AM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack    | QAChatDeployStack
Error occurred while monitoring stack: Error [ValidationError]: 2 validation errors detected: Value '' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*; Value '' at 'stackName' failed to satisfy constraint: Member must have length greater than or equal to 1
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:46430)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:90083)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:89531)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:196289)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:189841)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:154713)
    at /usr/local/lib/node_modules/aws-cdk/lib/index.js:362:155043
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:190133)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:196364)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:90251) {
  code: 'ValidationError',
  time: 2023-10-10T03:50:04.928Z,
```
  requestId: '6c2c60be-d17f-4747-b1d3-799b75d366b0',
  statusCode: 400,
[████████████████████████████······························] (16/33)

**Comment by taylord0ng** [comment]
https://github.com/aws/aws-cdk/issues/27445
Downgrade aws cdk to 2.93.0
